name: livo_app
description: "App Nativa Oficial de Vecinos y Residentes LIVO SaaS"
publish_to: "none"
version: 1.0.1+53

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
    - assets/logo.png
    - assets/icon.png